### PR TITLE
deprecate ?/+?/-? in favor of */+*/-*

### PR DESCRIPTION
**Pull request by martijnhoekstra**
Resolves https://github.com/typelevel/kind-projector/issues/171

### CODE REVIEW

**Review by larsrh — APPROVED** [review]
LGTM

**Comment by SethTisue** [comment]
to test, I did `++2.13.4` and `publishLocal`, then with a `build.sbt` of

```
scalaVersion := "2.13.4"
addCompilerPlugin("org.typelevel" %% "kind-projector" % "0.11.2-SNAPSHOT" cross CrossVersion.full)
```

I ran `sbt console` and tried a few examples from `test.scala`.

That all went fine, so I just have one piece of feedback. Maybe change:

    warning: ? syntax is deprecated. Use * instead of ?

to

    warning: kind-projector's ? syntax is deprecated. Use * instead of ?, to enable transition to Scala 3.

if a reason is given it feels less annoying, and mentioning "kind-projector" makes it clear to a hypothetical new-to-Scala maintenance programmer where the warning is even coming from.

**Comment by martijnhoekstra** [comment]
Sure! There is some design space for verbosity of the message and what scala versions to warn on. I went with a simple warning for all versions, with the argument that people using type lambdas and partially applied types will probably have a decent idea of what's coming up in the scala ecosystem and would be more helped by less cluttered warnings than by details about how `?` and scala 3 interact.

The real solution is probably referring to the scalafix re-writing the the deprecated syntax that I should have written instead.

**Comment by martijnhoekstra** [comment]
> kind-projector ? placeholders are deprected. Use * instead of ? for cross-compatibility with Scala 3

**Comment by martijnhoekstra** [comment]
I confirmed that the following scalafix makes the correct replacements in the test file:

```
package fix

import metaconfig.Configured
import scalafix.v1._
import scala.meta._

class DeprecatedKindprojector extends SemanticRule("DeprecatedKindprojector") {
  override def fix(implicit doc: SemanticDocument): Patch = {
    doc.tree
      .collect {
        case inv @ Type.Name("?") => Patch.replaceTree(inv, "*")
        case cov @ Type.Name("+?") => Patch.replaceTree(cov, "+*")
        case contrav @ Type.Name("-?") => Patch.replaceTree(contrav, "-*")
      }
      .asPatch
  }
}
```

Maybe it'll help someone

**Comment by SethTisue** [comment]
s/deprected/deprecated/, otherwise LGTM

**Comment by SethTisue** [comment]
@larsrh do you think this merits rolling a release?

(I don't think it _urgently_ merits rolling a release, but OTOH, I feel like if we don't roll one, months might pass)

**Comment by larsrh** [comment]
Sure, will do.

**Comment by larsrh** [comment]
0.11.2 rolling out now :steam_locomotive:

**Comment by neko-kai** [comment]
@martijnhoekstra @SethTisue 
Is there a way to silence the warning globally besides downgrading kind-projector? 

`nowarn/-Wconf` do not work for warnings from compiler-plugins unfortunately: https://github.com/scala/bug/issues/12258

**Comment by SethTisue** [comment]
@martijnhoekstra interested in modifying the plugin to follow the advice given at scala/bug#12258 ?

**Comment by martijnhoekstra** [comment]
Sure, but I can't commit to any timeline.

**Comment by SethTisue** [comment]
#173

**Comment by SethTisue** [comment]
2.12.13 is out and includes `-Wconf` and `@nowarn`

**Pull request merged**
