### PR TITLE
Scala 2.13.13

### PR DESCRIPTION
**Pull request by armanbilge**

### CODE REVIEW

**Comment by armanbilge** [comment]
Hmm. It's not compiling as-is. That might complicate back-publishing 🤔

**Comment by armanbilge** [comment]
Yeah, the back-publish script doesn't work. I think we have two options:
1. modify the script so that it disables fatal warnings
2. accept that the day has come that the code needs to change and we need a new version.

**Comment by rossabaker** [comment]
It's sketchy to change the release script without changing the version, even if the rest of the code comes from the tag.  It's akin to having an unversioned sbt.  (Please forgive the author of #213.).  If these are the two options, then I think we ought to bump the version either way, and then might as well fix the code.

And once committed to that, turning off fatal warnings gives us more options if 2.13.14 brings new warnings.

**Comment by lefou** [comment]
First, Kudos for trying to (back) publish for newer Scala versions without bumping the version! But I think, it's fine to release a new version in this case.

**Comment by armanbilge** [comment]
Thanks for the feedback. I'll work publishing a new version today.

**Pull request merged**
