### PR TITLE
Add Scala 2.12.14

### PR DESCRIPTION
**Pull request by vasilmkd**

### CODE REVIEW

**Comment by rossabaker** [comment]
Do we bump the patch number on these or just backpublish?

**Review by rossabaker — APPROVED** [review]

**Comment by rossabaker** [comment]
I'll give that a try now.  I'm overrun with broken scala stewards.

**Comment by rossabaker** [comment]
I backpublished off the v0.13.0 tag with `++2.12.14!`. It's syncing now.

**Comment by vasilmkd** [comment]
It looks like it went through.

**Pull request merged**
